### ISSUE TITLE
Difficulty adjusting feeds list

### ISSUE THREAD

**Issue by philwonski** [marekq/rss-lambda#1]
Hi @marekq , really cool stack and thanks for the efforts on it. 

Everything works when I use feeds from the AWS blog; however, if I try other RSS feeds, the Dynamo table does not fill up. 

I don't see anything in the lambda.py that would prevent other feeds being parsed, especially since these feeds also have "title," "link," and "description." And it seems rss-vacuum.py is just to clean up the table, no fetching the feed and populating the table here. 

Any suggestions on the best way to tweak the parser to use feeds from other sites? Bit of a python noob... 

Thanks

Phil

**Comment by philwonski** [comment]
Retraction! 

For future googlers, I just updated the for loop for the article meta data that begins on line 182. In my case the feed I wanted to use had no "author" field so this must have hung up the db write. Switching "auth" to a known field in the RSS feed was all I had to do to make it work.

**Comment by marekq** [comment]
Hey @philippedubs ,

Thanks a lot for the feedback and pointers! I've written the code a while back to specifically read AWS RSS feeds, but I think it could easily be adopted to read other XML based feeds too. 

I haven't really figured out how to "dynamically" map fields from RSS to a DynamoDB schema and this is where you indeed could see some issues using another kind of feed. For me, having these specific fields is important in order to power other websites that directly read from the table, but I'm open to any suggestions or pull requests how to improve this. I could perhaps describe and make the field mapping a bit easier to edit for others. 

Finally, the RSS Vacuum script is used in a Lambda that I specifically need for one of these websites, it helps me to control the amount of read capacity needed for it in a very crude and simple way. I do not want to return simply all posts that came out in the last X days there, but only a fixed amount of postings per category (i.e. show me the last 50 items per category for the last 3 months, unless there significantly more posts that were discovered for the same period). I'll make sure to document this a bit better going forward.

In any case, feel free to message me if I can help with anything else, I'd love it if my solution helps you build something!

Cheers,

Marek

**Comment by philwonski** [comment]
:-) thanks Marek, makes sense!

**Comment by philwonski** [comment]
Let you know how I do!

**Comment by marekq** [comment]
I just updated the readme doc based on your comments and made some improvements to the deployment script and SAM template as well. I'll think of how to make the service work easier with other fields as well. 

Thanks again for the input!
